[package]
name = "boli-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "boli-server"
path = "src/main.rs"

[dependencies]
tonic = "*"
prost = "0.13"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tonic-reflection = "0.12.3"

[build-dependencies]
tonic-build = "*"