on: push
name: Linter

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
        working-directory: ./server
      - run: npm ci && npm run lint && npm run format
        working-directory: ./web
